
name: Build APK

on:
  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio al ejecutor
        uses: actions/checkout@v4

      - name: Instalar el JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Compilar y construir apk Gradle
        # clean limpia los archivos temporales y de compilacion antiguos
        # assembleRelease  compila el código fuente y crea el APK de lanzamiento
        # test ejecuta las pruebas unitarias que hayamos definido en el proyecto
        run: ./gradlew clean assembleRelease test

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: unograham-release
          path: app/build/outputs/apk/release/unograham-release.apk
